### PR TITLE
Corrected the keystroke required for Formatted Preview

### PR DESCRIPTION
**Pull request by OgierM**
It now reflects the actual default value.

### CODE REVIEW

**Comment by OgierM** [comment]
#14 #15

**Comment by superlou** [comment]
I believe the intent of `ctrl+alt+M` was to show that it should be "capital m," that is, the shift key should be held.  So, while it is currently technically correct, if `ctrl+alt+shift+m` would save some misunderstandings, I don't see a problem with this change.  Is there any kind of standard on how other Atom packages document their hotkeys?

**Comment by OgierM** [comment]
@superlou I looked at some other packages and 

> `alt`+`f4`

seems to be the way to go in terms of formatting.

**Comment by superlou** [comment]
Not to be super difficult, but how does the atom-build package do their fancy shortcuts notation [in their readme](https://github.com/noseglid/atom-build)?

**Comment by OgierM** [comment]
Did that, looks <kbd>better</kbd> now

**Pull request merged**
