### PR TITLE
Outline Reorder Nested Elements

### PR DESCRIPTION
**Pull request by jrbostic**
Rules:
1) Parent cannot be moved into its self or own child/grandchild/etc.
2) Movement of parent under a sibling will adopt sibling's trailing child/grandchild/etc. (post insertion point)
3) Synopsis elements are not individually movable

Supported:
1) Movement of elements among all positions equivalent in hierarchy
2) When scenes are hidden, child scenes are considered a part of their parent heading

### CODE REVIEW

**Comment by superlou** [comment]
The included tests pass.  I noticed that if I move a lower level section into a higher level section, the content is moved correctly, but the outline shows the wrong indentation for the section.  For example:

```
# Section 1
## Section 2
### Section 3

INT. DIM HOUSE
We're going to move this scene using it's section.

RONALD
Let's do it.
```

Then, drag Section 3 right after section 1.

```
# Section 1
### Section 3

INT. DIM HOUSE
We're going to move this scene using it's section.

RONALD
Let's do it.

## Section 2
```

This is the expected result, and Section 3 keeps the proper number of #s.  However, the outline shows Section 3 and Section 2 with the same indentation.  I think this might be expected since this is a somewhat undefined situation, where a 3rd level section has no 2nd level section to exist under.

In hindsight, this has the same issue if you were to just create this sort of undefined section nesting from the start, so maybe this is a separate bug report.

**Comment by jrbostic** [comment]
That's an interesting point.  Yea, I think there's a point where we have to accept that users can do weird stuff... I'm not entirely sure if this is something we can prevent.

**Comment by superlou** [comment]
I guess you could automatically change heading levels to be one less than the identified parent; however, if someone's moving things around in multiple steps, that might get confusing.  Another option is we could start adding linting features using Atom's built-in tools to warn a user if we see something invalid.

**Comment by jrbostic** [comment]
Personally, I'd rather see hints to end users rather than text modification.  The way that this reordering works is lossless, so they never have a piece of text modified by fountain package.  It only moves blocks of code to valid locations.  A linter sounds like a really cool idea.

**Comment by superlou** [comment]
I agree.  A linter seems less heavy-handed, and it's probably worth a new ticket to keep the scope of this one manageable.

**Comment by jrbostic** [comment]
@superlou Alright.  I'm feeling pretty good about the testing on this now.  I think it will catch breaking changes across a variety of drag/drop scenarios.  It will almost certainly signal an alarm if any core logic is broken.

**Comment by jrbostic** [comment]
@superlou Just wanted to check in on this.  Is there something more you were looking for here?

**Comment by superlou** [comment]
I'm still nervous about how the level of the section in the outline may differ from the level of the section in the markup because of the indentation being based on nesting.  That said, I'm willing to merge it to trunk and handle other weirdness as other issues.

**Pull request merged**
