### PR TITLE
Basics of Export to PDF

### PR DESCRIPTION
**Pull request by jrbostic**
* Button absolutely positioned at the top right of panel body
screenshot from 2017-09-08 15-57-26
* Click to convert current fountain file displayed in preview
* Saves to current directory root
* Success message when file saved
* Confirm dialogue on overwrite
* Package configuration file to set default conversion aspects
* Unit tests for logical branches

Possible future features:
* Adding a configuration UI to set the config properties used by conversion tool
* Find better docking location for export button (one that's always visible)

Notes:
I really wanted the button to be fixed to the top right... but that didn't play well with multiple panels.  Not ideal, but I wasn't sure how to dock it anywhere else.

I'm worried that my package.json additions might be insufficient for deploy (if the package does in fact deploy with only a subset of files from the original node modules).  Hopefully someone can check that.

I did my best to identify/solve possible cross OS issues with the command execution, but I can't test windows or mac myself.

### CODE REVIEW

**Comment by superlou** [comment]
Is there any chance that Afterwriting can also be responsible for generating the HTML in the preview window?  I'm concerned about maintaining a third Fountain parser.  Afterwriting seems more thorough than what we currently have, so it would be great to use that and avoid having inconsistencies between the preview and PDF views.

**Comment by jrbostic** [comment]
I started looking into that.  I think there's a PDF view package that could maybe provide it.  Would just have to figure out a system of storing temporary PDFs... Trigger creation... Update display.  And that would fit better with the idea of allowing the user to configure output.

**Comment by jrbostic** [comment]
Of course... It wouldn't be HTML.  And it does force us to address a question about whether the preview isn't the same as just downloading the PDF... Because it will generate a file, but we won't want to implicitly overwrite an existent copy that the user wants to keep.  And we'll want to make sure we clean up any additional generated files.  And figure out how to get a download button back in there.

**Comment by jrbostic** [comment]
https://github.com/izuzak/atom-pdf-view/blob/master/lib/pdf-editor-view.js 

That's the view that this other package uses.  Obviously, I don't know a whole lot about pulling from other packages.  My assumption is that you can construct this with a file path for viewing, but adding a "download" button to the view might require some other hackery.  I'm mulling this over but haven't seen a real clear vision of an intuitive solution.

**Comment by superlou** [comment]
What about instead cleaning up the existing HTML preview to be more standards compliant and using something to [go from HTML to PDF](https://www.npmjs.com/package/html-pdf)?  That might be easier down the road if we want to be able to keep the "code" and the preview vertically aligned down the road.  I'm not sure how you'd go about it with a PDF in a pane.

**Comment by jrbostic** [comment]
That idea definitely has some perks.  I guess if you can pass your css through that would be more consistent.  One benefit of the afterwriting module to consider is its ability to be configured.  I would see that as a big ticket item for the fountain package in the future... But that would require a custom implementation if you go HTML conversion route.  I'll take a look at it tonight and see what it might take to get all those styles applied via html-pdf.

**Comment by jrbostic** [comment]
Ah, yea, I'm starting to understand better the nuances of this problem.  

One option is to tentatively configure the afterwriting to appear like the HTML view (which I actually tried to do),.  That's exampled by the PR.  But this approach wouldn't be long-term viable if you ever choose to go configurable because the PDF and view would be out sync with HTML.  Future work would include either going all PDF or modeling HTML view on afterwriting config.  So, it's probably a step in the all PDF direction.

The HTML option... building from HTML is desirable from the perspective of reusing your existent codebase.  However the CSS styles probably aren't going to port to PDF... And I couldn't find anything offering to do that readily.  So, it would be work to figure out how to use those headers and whatnot to approximate the HTML view.  That's sounding the most painful to me.

And the third is displaying PDF right from the get go and figuring out the download workflow and display.  This would solve the long term issue of syncing the two, but takes additional upfront work.

I guess in order of desirability in my mind, I would say:
1) All PDF 
2) Half/half (imperfect but a step towards all PDF)
3) HTML to PDF 

Does that sound right?  Any other options?

**Comment by jrbostic** [comment]
Just want to throw this out there.  Maybe you don't need the preview if you offer a PDF generation function.  Alternatively, you could move the PDF generation button to the outline, scrap the HTML preview panel... then just generate and open the PDF with the pdf-view package.  Then these dilemmas disappear... And fountain package is just one panel...

**Comment by superlou** [comment]
As background, the preview came from when I developed a [Google Docs add-on](https://chrome.google.com/webstore/detail/fountain-tools/jfkgfigdnpiljgakkbnppfipajogbjdl?hl=en).  The development environment for add-ons is pretty rudimentary; however, there is a one-liner to convert HTML to PDF that did a good job of respecting CSS.  The preview was added as a feature since I already had presentable HTML and it was convenient to identify user errors with Fountain syntax without having to generate a PDF, open it, and scroll to the right place every time.

So, In my personal use case, the preview doesn't need to be HTML.  I don't *think* people use the preview window as they write, especially since it doesn't remain synced vertically on a long script.  I do think there is value in being able to diagnose Fountain typos without leaving Atom.

My compromise would be to have an ability to generate and display snippets of script inside an Atom preview.  If this is done by only running Afterwriting on the selected text in the code editor, rendering a PDF, and opening it in Atom, I'm cool with that.  Is this something Afterwriting can do quickly (< 1 sec)?  I like that this offloads the script generation to Afterwriting, which specializes in the task, and we can focus on other editor related functionality.

I'm hoping some other developers/users might way into this pull-request before we make the change (@morekitsch, @OgierM), though in my experience we'll only find out once people start sending nastygrams.

**Comment by jrbostic** [comment]
So, just wanted to check in where we're at on #20 and #23 

I see that I've got some unsurprising conflicts with the changes to package.json (nice to have that cleaned up though!)... and both of my branches will ultimately conflict with each other in that file... but is there something more that you guys are looking for from either of these?  Is there one or the other that is closer to being accepted?

**Comment by superlou** [comment]
Thanks for the ping.  I will look at #20 tonight.  I had a weird issue where I dragged an element, and then everything disappeared, but I haven't been able to recreate it or track down what might have caused it.

On this PR, my thoughts are to do the following:

[ ] If the user has not selected any text inside the editor, the formatted-preview (ctrl+alt+shift+m) shall render a preview of the full script in Atom using Afterwriting.
[ ] If the user has selected text inside the editor, the formatted-preview (ctrl+alt+shift+m) shall render a preview of the selected script (logic TBD) in Atom using Afterwriting.
[ ] With the same selection logic as in the previous two requirements, add a new command to save the Afterwriting PDF.
[ ] Add a new command (legacy-preview, no default shortcut) so that someone who really wants the old preview can get it.  We will mark this deprecated in the docs, so anyone grieving can complain about it.
[ ] Release a minor (pre-1.0.0) version with these features.
[ ] Remove the legacy commands and code at the next minor rev., or at 1.0.0.

This will let us switch to Afterwriting and deprecate the old stuff.  Since it uses the current commands to trigger the new preview, if anyone is really getting useful behavior from it, they have a chance to complain when they see it.  Does this seem like a reasonable checklist to evaluate this PR?  I'm not too concerned with PDF generation buttons since Atom is big on the ctrl+shift+P commands list, but if they're working it's a nice thing to have.  If not, we can always add the buttons later.

**Comment by jrbostic** [comment]
That sounds like a good plan to me.  The only thing I'm unsure of is the best way to manage exporting.  I suppose it could just be triggered by the keyboard command for preview, but you still have the issue of overwriting a saved PDF if you do that... And I don't want a user to be prompted on every save about overwriting.  But I do think they ought to be prompted.  Maybe separate commands for preview and export, where preview creates an unseen temp file in the fountain package?

**Comment by superlou** [comment]
I like the idea of the preview being a "hidden" temporary PDF.  You may need to do some cleverness to handle the case where someone has multiple previews open or is reopening the editor and has to deserialize the previous state.

Then, when the user wants to "generate" a PDF, it would present them with a prompt suggesting a PDF name based on the script filename, so you simply have to press enter.  You could have a warning underneath the prompt if the new file matches an existing one that they are about to overwrite a previous PDF.  Unfortunately, that makes the normal workflow have an extra "enter" press, but that's better than having to click something.

**Comment by jrbostic** [comment]
So, my current branch already does rendering based on the associated window id and creates time-stamped temp files... And accesses both files in the package and local directory in a cross-platform manner... So, I don't anticipate much additional research.

There is already a file overwrite prompt... With tests... As well.  So that should be easy.

The only unknowns are displaying the PDF, deserializing on startup, and rendering selected text (all of which are probably not of high complexity with atom hooks and a callable PDF viewing package).

**Comment by superlou** [comment]
Just tried it out.  When it works, the Afterwriting output is excellent.  If we can display the PDF inside Atom and it's performant, I'm sold on replacing the hacky HTML based preview.

Were you able to generate a PDF of *The Last Birthday Card*?  I'm getting the following:

```
Uncaught Error: Command failed: node /home/lsimons/github/fountain/node_modules/afterwriting/awc.js --source tmp1506555195898.fountain --pdf The Last Birthday Card.pdf --config /home/lsimons/github/fountain/configs/afterwritingConfig.json --overwrite
fs.js:540
  binding.open(pathModule._makeLong(path),
          ^

TypeError: path must be a string
```

Also, do temporary files ever get cleaned up?

**Comment by jrbostic** [comment]
So, I've never seen that error.  Curious.  I do have code that cleans up temp files via fs.unlink... but if there's a failure along the way it may not be reaching that block.  Could probably work in some unconditional cleanup though.  I can pull it down and try to troubleshoot after resolving conflicts in #20.

**Comment by jrbostic** [comment]
And, yes, I was able to generate on the last birthday card.

**Comment by jrbostic** [comment]
Okay, so, I've resolved conflicts and am actively working on the checklist above.  I've already identified an edge case pathing issue for the output file, so that's good to have noticed.  And I've just comprehended the error you ran into... I did run the birthday card conversion... _but I renamed the file_... lol!  So, yea, it's just the whitespace in the name.  I'll look at some cross-platform solutions for command line paths with whitespace, but that's probably a slam dunk otherwise.  Then the checklist.

**Comment by jrbostic** [comment]
Update:

I was able to pull in the pdf-vew package via package-deps package.  That's cool because it optionally prompts the user about installing the dependency... and then installs and loads it as a normal package on the fly.  The pdf-view then makes itself the default for pdf files.  But I'm having a really hard time getting atom to open a tab instead of a new window.  Also, PDF rendering is notably slower than your html view.

To deal with the file opening, I've tried activating the pdf view manually (passing the path)... and that will execute the code, but does not open the new pane.  And I've tried "atom.open"... which refuses to open a new tab... it insists on opening a whole new window (even with the ".newWindow" set to false).  I've looked through various issues and scoured the internet for the obvious stuff... but no solutions seem readily available.  I'm feeling a little disheartened by this.

Any wisdom, ideas, or thoughts on the issue?

**Comment by jrbostic** [comment]
Woohoo!  Finally found it: "atom.workspace.open"... I knew it had to be somewhere.  Now it's just a matter of figuring out a refresh approach on save... and assessing performance.

**Comment by jrbostic** [comment]
Good news... great news... the pdf view automatically rerenders on file persistence (and it's way faster than the initial workspace opening), so it's looking pretty good.  I've still got a lot of work to get the commands setup and properly organize the code, but I think I've got the core pieces validated.  As far as I can tell, now it's just a matter of tedious refactoring work and updating tests.

**Comment by jrbostic** [comment]
Okay, so... I tried to follow your checklist as best I could.  I started to realize that I didn't fully follow some of the command rearranging ideas, so I just added some new ones for demonstration.  The big things remaining are cross-platform pathing updates and tests.  I'd appreciate some feedback if anyone finds time... just so I don't get to testing and find out that everyone hates some particular choice.

* fixed whitespace file name error that was identified
* added atom commands to export and preview pdf
* added temp folder to project for storing preview files
* ensured exports actually save to the folder/subfolder of .fountain file
* added button on outline view to call through pdf export logic
* while I was there, docked the outline panel header to the top and pushed hide scene checkbox in there
* commented out legacy preview export button (tentative)
* bound the preview generation/refresh to save events on the original fountain file

**Comment by superlou** [comment]
I'm probably missing something, but when I try to preview/export a PDF, I receive an `initiateConversion` is undefined error in `fountain-pdf-converter.coffee` at lines 8 or 11.  It looks like these are calls to instance methods, so should those be preceded with `@`?  That makes it work for me, though I don't know how it would work for you otherwise.

With respect to the commands and shortcuts, I suggest we do something like this:

```
# fountain.coffee
@subscriptions.add atom.commands.add 'atom-workspace',
  'fountain:toggleOutlineView': => @toggleOutlineView(),
  'fountain:preview_legacy' :=> @preview(),  # deprecated, remove in a later release
  'fountain:preview' :=> @pdfPreview(),
  'fountain:export_pdf' :=> @pdfExport()

# fountain.cson
'atom-text-editor':
  'ctrl-alt-o': 'fountain:toggleOutlineView'
  'ctrl-alt-M': 'fountain:pdfPreview'
  'ctrl-alt-X': 'fountain:pdfExport' 
```

This way anyone using this package will start getting PDF previews when they do the "default" preview.  I want to make sure we start getting some community feedback ASAP if it breaks anyone's workflows while they can still access the legacy version.

When doing a partial preview (by selecting a chunk of a script), it seems like there's always a blank title page.  Is it possible to tell Afterwriting to not include a title page when "preview by selection" doesn't include one?

The only other thing I think is worth investigating before we merge this is if it's possible to generate the PDF in an asynchronous task.  On my computer, when I run preview on something like *Big Fish*, Atom is locked up for around 6 seconds.

**Comment by jrbostic** [comment]
Oh, silly me.  I did some work on tests as my final thing last night and moved those back to instance methods to hit them more directly...  It was late... Must not have manually tested.

I'll switch those commands out tonight.  But how do they access the legacy preview without a command?  Do they set it up via config or something?

I did notice the partial preview thing.  Afterwriting has a config property for that... And could probably be removed, but will have to create an additional config file and select conditionally (I think)... To keep support for title page on normal preview/export.

Async file creation is possible.  I originally had the converter written that way but was having problems writing tests because I couldn't check for file existence immediately after execution.  I can take a second look.

**Comment by superlou** [comment]
> But how do they access the legacy preview without a command? Do they set it up via config or something?

They should still be able to do `ctrl+shift+p` and then type the first few letters to get the legacy command.  I think we'd put an explanation in the readme until we take away the deprecated feature.

The only reason I think async preview is worth holding off a little is because `ctrl+s` triggers an update, and it's odd behavior to freeze up Atom while the user remembers to close their large preview.

**Comment by jrbostic** [comment]
And actually, the more I think about it, rendering the selected text becomes a larger problem to solve.  To do what you described above would take 2 separate config files and some additional text parsing to determine if a title page is included.  Or... Potentially... Writing a single config on the fly to pass in.  I'd sort of like to see this pulled into a separate task.  It seems like more of a bonus feature to me.  Also, since I was hoping to look at user-defined configuration in the foreseeable future, maybe it would be better appended to that work (to take into account all requirements for afterwriting configuration)?  What say you on that?

On that topic, I know you haven't said much about the user configuration of afterwriting.  Are you on board with that idea?  Providing package configuration that targets afterwriting configs?

Either way... Design-wise, I think it would make sense to create a separate service/class to manage afterwriting configs, so there's a proper division of purpose.

And sorry if I sound like a broken record about trying to split up tasks... I just do a little better with more modular units of work... Helps me conceptualize... makes me feel like I'm getting stuff done... And it also opens up tasks for others who might be interested.

**Comment by superlou** [comment]
No problem.  I completely understand the idea of separating it out.  The name of this task is "basic export to PDF," and you've done a great job with that.  I think I would prefer to hold off on an APM release of until async generation is examined, but I'd be happy to merge this PR after the little things we discussed are covered.

I'm fine with making Afterwriting config files a separate task and I like the idea.  I think we could make a lot of the Afterwriting configuration items into the Atom package's settings.

**Comment by jrbostic** [comment]
I agree about async files.  I'd like to address that on this branch, since it was my original intention.  Probably just a promise chaining issue.  I'll let you know when I figure it out.

**Comment by jrbostic** [comment]
Async pdf conversion implemented.  Tests updated.  And geez.... Jasmine async tests are hard!  You can write passing tests that aren't actually hitting the "expect" statements (scary)... which I know from experience... but getting them to accurately pass... wow... I'm just floored by the complexity of it.  But please check out the branch and have another look.  Performance and general UX are much better.  I also added a notification when PDF generation begins to sort of indicate that the user's command registered.

**Comment by jrbostic** [comment]
@superlou As far as I know this is ready to go whenever you are.  I addressed the command rearrangement and updated readme.

**Comment by superlou** [comment]
@jrbostic I got stuck at the studio late tonight.  Will try to review and merge as soon as I get back from the office tomorrow.  Sorry for the delay.

**Comment by jrbostic** [comment]
@superlou Not at all.  Thanks!

**Comment by jrbostic** [comment]
@superlou did you try running the commands from keyboard after that change?  I was having an issue where keyboard commands were being ignored when the names didn't match with the keymap file.  Maybe I was confused?

**Comment by superlou** [comment]
You're right.  Long day.  Fixing now.

**Comment by jrbostic** [comment]
It's easy to miss.  I originally just copied in your commands and didn't notice for a while.  But we can always swing in for a name refactor... Or see if commands have alias support of some kind.

**Comment by superlou** [comment]
Are they not working for you still?  They are working for me (ctrl-alt-O, ctrl-alt-M, and ctrl-alt-X).

**Comment by jrbostic** [comment]
Oh, I'm making dinner ATM.  I didn't actually pull it down yet.  Just a hunch.  I'm sure you got it.

**Comment by superlou** [comment]
Roger. :)

**Comment by captaindooley** [comment]
I have nothing valuable to add to this conversation - I just wanted to thank you guys for working so hard on this.

I will confirm how superlou suggested people use the preview function is exactly how I use the preview fuction - just to check errors of whatever I just wrote - and I don't leave it open otherwise.

**Comment by jrbostic** [comment]
@captaindooley You should still be able to use that workflow with the new PDF preview.  The main difference will be added user notifications, since PDF generation and display takes just a tad longer than the old preview.  There's also the traditional support that updates preview on a save to the original fountain file.

**Comment by captaindooley** [comment]
Copy - I picked up on that reading through the past few days - I just thought I'd add my agreement to superlou's assessment.

**Pull request merged**
