### PR TITLE
Replaced flatten with extend

### PR DESCRIPTION
**Pull request by superlou**
This appears to address the issue in #69 (and a few others). I'm not sure how this was working before, so I'm nervous about merging this quickly without confirmation that this was really the root of the problem.

### CODE REVIEW

**Comment by jrbostic** [comment]
I'll do some validation asap.

**Comment by jrbostic** [comment]
Underscore-plus was pulling in underscore 1.6.0 until June of this year.  And then they did a patch release that updated the underscore version to 1.8.3.  Flatten was rewritten somewhere in between.  Case closed.  

I like your code better anyway.  :)  Works great!

**Comment by jrbostic** [comment]
Also, there's always the option to nail down dependency versions to avoid breaks like that... we'd just be giving up automatically staying current.

Another thing is that the spec tests actually failed on this, so if you ran them locally before the release and they passed, its probably because you had a stale node_modules entry for underscore-plus.  Tricky.

**Comment by jrbostic** [comment]
And that's certainly why I couldn't reproduce the problem...

**Comment by superlou** [comment]
Awesome sleuthing. I'm going to release a patch tonight.

I noticed the spec tests failing when I pulled down a fresh copy of the package. It's probably worth looking at pinning down versions of packages we rely on, since even if we can catch a regression via tests, most users can't. I also might look into our use of underscore. If it's only one or two places for basic functionality, it might be able to fairly cleanly just address it with CoffeeScript syntactic sugar. Either way, I'm going to release the fix as soon as I can.

Do you want to be added as a collaborator for this repository?

**Comment by jrbostic** [comment]
Oh what's in a name!?  But yea, I'd love to be a collaborator!  :D

**Comment by superlou** [comment]
I actually thought you already were one. Invite sent.

**Comment by jrbostic** [comment]
Accepted!  Mwahaha.  ;)

**Pull request merged**
