### PR TITLE
added scene drag/drop reordering and toggling mechanism

### PR DESCRIPTION
**Pull request by jrbostic**
This is just a pull request to get some feedback before I do any more work... although I think the hard part is pretty much over.  I still need to refactor a little for cleanliness (like pulling the sortable list creation into its own function).  

Oh, and I need to target the original file for replacement instead of creating a new one.  I'll dogfood that myself before I'm done.

Also, I couldn't figure out how to pull in my node requires with the {} notation for assignment... don't know if that's important... although I'm assuming it is.

And I've never seen such a huge package.json.  Not sure if there's step I'm missing there.

Other than that, let me know of any questions or concerns.

Here's what the toggle looks like (defaults to locked):

screenshot from 2017-09-05 03-31-12
screenshot from 2017-09-05 03-30-54

### CODE REVIEW

**Comment by jrbostic** [comment]
So, currently, this is my list of things to do...
1) Figure out lock scoping issue when switching fountain between files (arising from my ignorance of coffeescript and whatnot... I'm close on this one)
2) Figure out why ctrl+Z disables order editing until file save
3) Figure out how to move requires out of view class
4) Explore difficulties of testing view (Idk... this is probably the hardest part)
5) Organizing the new code

superlou, are you willing to add this functionality if completed?

**Comment by superlou** [comment]
Absolutely.  I'd love to have decent tests on this, since it's the first function we've added that can actually break someone's document.

**Comment by jrbostic** [comment]
I totally agree... It's unforgivable to have a package that messes up your document.  I've worked with Jasmine via AngularJS frontend test tools, so I've got decent familiarity with the approach.  But since there are some new variables for me here, it's probably a week or two out before I can wrap this up.  

Do we just want to toss all the spec files in that same top level spec folder?

**Comment by superlou** [comment]
That sounds fine so long as everything has sane names.  If we can find a similar package doing something that works better or some other recommendation, I'm open to ideas.  I've been pretty hypocritical in that most of the existing functionality doesn't have tests (though it would be great if it did).

**Comment by jrbostic** [comment]
Okay... from my list above... 1, 2, and 5 are done.  I'm going to ignore 3 for now, since there's either a simple solution or it doesn't matter (I don't know which).  Moving on to creating some unit tests.  I'll browse around a little and see what can be done.

Additional Details (optional):

Issue 1 was created by event handlers being created/stacked on each list update (for preexisting code also).  Since this was a problem in common, I did a quick fix for all of the handlers and created a management structure to toss them before generating the new ones.  A better solution would probably be to recycle them... maybe a future task.

Issue 2 was that I needed to write to the text editor buffer instead of overwriting the file.  Overwriting the file, the current buffer data would win for Atom editor display priority.

**Comment by jrbostic** [comment]
So, here's what's up...

I added unit tests for the component pieces of sorting.  I also added minimal supporting unit tests for the list formatting functions that were originally there.  That way, if something changes at the original formatting stage, then you'll see a failure there first.  They're all based on a new fountain file that I added.

I tried to abstract as much as I could so you could understand the tests, but I sort of hand-jammed some of the complicated stuff... (really, this is where something like AngularJS protractor test framework would be much easier)...  but I did manage to cover all the logical branches of the dangerous pieces of new code.

While working on this, I came across two issues (not sure if they're related):

1. The module appears to have trouble deactivating during the test cleanup phase.
2. The package complains that it's not serializing properly in the console... constantly... in dev mode.

I don't know if these issues are related to my OS (Fedora 23), my version of Atom (1.17.1), or what... but I don't think that they were introduced by the work that I've done.  The second one was happening when I first started working... while the first one you wouldn't see unless you're loading/unloading the package.  Are these things that you've seen?  Should I log some new tickets?

**Comment by superlou** [comment]
@jrbostic I could've sworn we had a ticket for the second item about not serializing properly.  I used to see it and was trying to track it down, but then it stopped and I couldn't recreate it.  I'm on Linux Mint 18 with Atom 1.19 now.  I'm fine making tickets with steps to recreate, so we can take care of them.

When I initially made the package, it was back in the pre-1.0.0 Atom days and was my first attempt at making an Atom package.  It's very possible that I've done something that is either no longer a recommended practice (or never was). It would be really good to nail these down, as they sound like fundamental package problems as opposed to application logic bugs.

**Comment by jrbostic** [comment]
Okay, so I tracked both of those down to fountain.coffee file. They were both related to calls to an instance property called PreviewView that was never assigned a value.  Removing did not impact the package behavior.  Looks like file could still use some cleanup... to figure out what is actually being used and remove superfluous code.  Anyhow, that's all the work I intend to do in this branch unless otherwise required.

**Comment by superlou** [comment]
@morekitsch I'm stuck away from a development computer for a few days, so I can't try this out properly.  If you have a chance to look at it and give it a thumbs-up, I'll merge and release a new minor update.  

Otherwise I should be able to take a look on Monday evening, sorry.

**Comment by jrbostic** [comment]
After discovering problem with the overlay absolute positioning of the red X over the lock (because the panel header actually scrolls with the panel body for this view), I decided to swap out for the octicon key icon instead to indicate unlocked.... that way I could just toggle the classes on a single span. 

screenshot from 2017-09-08 15-03-02

Obviously I'd rather have an unlocked lock icon!  So, I didn't want to spend a bunch of time fiddling with that and just settled for "good enough".  Maybe in the future, an unlocked lock icon will become available or some other contributor will feel compelled to pull in another icon dependency.  That just felt like busy work at this point.

**Comment by superlou** [comment]
Can you address the conflicts?  The package.json ones are trivial, but I want to make sure you weren't using any of the cruft deleted in fountain.coffee.

It seems to work great for dragging scenes.  My only concern is that when dragging sections, it does not drag the child elements underneath it.  Is that intentional?  This makes it tricky to move any item that has children.  What are your thoughts on making parents drag their children by default?

Bikeshedding idea: since the "key" to mean unlocked is a little confusing, how about just making the lock icon nearly transparent when unlocked, and opaque when locked?

**Comment by jrbostic** [comment]
I will try and address conflicts this evening.  I probably was not using anything from fountain.coffee; pretty sure it was just cleanup to kill the console errors.  The current dragging of scenes only was intentional (and developments in the code were documented in PR and issue for reference).  Dragging children with parents is somewhat more complex and requires more complicated testing.  I already did quite a bit of refactoring, new code, and testing to get this basic stuff working correctly.  I had requested to address the parent moving separately.  I do have an idea of how to do it... And I will commit to do it myself... I'd just prefer to split up the work a little more.

**Comment by superlou** [comment]
Sorry I forgot about the separate request.  I'm find adopting this PR and addressing the parent-child dragging later.  Do you feel that this functionality is enough to warrant a release, or would you rather keep these improvements in master, and release when the whole feature is complete?  I'm OK with either, so long as the readme identifies the expected behavior.

**Comment by jrbostic** [comment]
When it's released is not a huge issue to me.  My current personal priority ranking is...

Resolving conflicts here 
Getting new PDF stuff working 
Refactoring the outline view to serialize properly
Adding hierarchical dragging

Probably a few weeks worth of work.  And for personal use, I'd like to have it all.  That being said, I find this feature more useful than not having it at all, so it's arguable.  The potential of getting feedback from users before adding more also sounds useful.  Idk.

If you'd like to proceed with release, I'll update the readme this evening.

**Comment by superlou** [comment]
I'll merge the PR as soon as the conflicts are handled.  Then it can get released (and the readme updated) with the PDF stuff.  I just don't want you to feel like your contributions are stuck in PR quicksand.

**Comment by jrbostic** [comment]
I appreciate that.  That is definitely part of my nervousness about doing too much work in one branch... making sure that the features will be available to end users (a group in which I'm included).  But I also understand the sacrifice/responsibility of being the repo owner, so patience is important.  

Anyway... sounds like a good plan to me.  Also, thanks for all of your efforts.  I'll press on as described.

**Pull request merged**
