### PR TITLE
use buffered process for pdf conversion and disallow unsaved

### PR DESCRIPTION
**Pull request by jrbostic**
Addresses issue #35 and beyond (documented in that issue).

### CODE REVIEW

**Comment by jrbostic** [comment]
Looks like I hadn't provided very well for Windows paths originally.  Figured improving that now would save the project an inevitable future issue.  I converted paths to rely on `path.join`, ran spec tests a few times, manually tested conversion... so, hopefully it just works across the board now (as unlikely as that is, given experience).

**Comment by superlou** [comment]
Works good for me, though I don't have a Windows PC to test on.  Are you comfortable merging and releasing now?

**Comment by jrbostic** [comment]
I am.  I also can't do the cross platform testing, but I did some reading about it and I think we're in a better position all around regardless.

**Comment by superlou** [comment]
Released with 0.6.1.

**Pull request merged**
